### ISSUE TITLE
Add a License please!

### ISSUE THREAD

**Issue by nerdachse** [Vixeliz/bevy_tileset_integration#1]
Well, basically the title.

Thanks a lot for putting this on the internet and... eh... maybe open sourcing it *scnr* ;)

**Comment by Vixeliz** [comment]
Sorry never added one cause this isn’t finished yet atm it doesn’t have autotiling or documentation yet but Ill add mit for the time being if you would like to mess with it at all

**Comment by Vixeliz** [comment]
There we go dual licensed under mit and Apache!

**Comment by Vixeliz** [comment]
Just as a warning idk when I will get around to adding those features right now a lot of my time is being spent on a voxel engine similar to Minetest but I do plan to finish this up at some point hopefully.
